/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        'p': ['var(--font-family-p)'],
        'p2': ['var(--font-family-p2)'],
      },
      fontSize: {
        'caption': ['12px', { lineHeight: '1.45' }],
        'supporting': ['13px', { lineHeight: '1.45' }],
        'body': ['14px', { lineHeight: '1.55' }],
        'base-lg': ['15px', { lineHeight: '1.55' }],
        'card': ['16px', { lineHeight: '1.3' }],
        'quote': ['18px', { lineHeight: '1.6' }],
        'card-title': ['20px', { lineHeight: '1.25' }],
        'subheading': ['20px', { lineHeight: '1.3' }],
        'heading-sm': ['22px', { lineHeight: '1.25' }],
        'metric-value': ['24px', { lineHeight: '1.2' }],
        'metric-label': ['13px', { lineHeight: '1.4' }],
        'hero': ['clamp(46px, 4vw, 60px)', { lineHeight: '1.06' }],
        'p': ['16px', { lineHeight: '1.45', letterSpacing: '0.02em' }],
        'p2': ['14px', { lineHeight: '1.55', letterSpacing: '0.02em' }],
        'section': ['clamp(42px, 4vw, 58px)', { lineHeight: '1.08' }],
        'display': ['clamp(48px, 4.5vw, 64px)', { lineHeight: '1.06' }],
      },
      letterSpacing: {
        eyebrow: '0.02em',
        hero: '-0.035em',
        display: '-0.045em',
        label: '0.12em',
        footer: '0.14em',
      },
      colors: {
        orange: {
          DEFAULT: '#f07f25',
          dark: '#C55F0D',
        },
        'zenbg': '#06141F',
        muted: 'var(--text-muted)',
        line: 'var(--line)',
        card: 'var(--card)',
        'zen-bg': 'var(--bg-gradient)',
        'zen-card': '#242424',
        header: 'var(--header)',
        'nav-surface': 'var(--nav-surface)',
        'nav-card': 'var(--nav-card)',
        'nav-navy': 'var(--nav-navy)',
        'nav-ink': 'var(--nav-ink)',
        'nav-muted': 'var(--nav-muted)',
        'nav-line': 'var(--nav-line)',
        'hover-surface': 'var(--hover-surface)',
        'zen-text': 'var(--text)',
      },
      keyframes: {
        'caret-blink': { '0%,100%': { opacity: '1' }, '50%': { opacity: '0' } },
        'caret-flow': { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.25' } },
        'data-flow': { to: { strokeDashoffset: '-20' } },
        'network-pulse': { '50%': { transform: 'scale(1.04)', opacity: '0.75' } },
        'core-glow': { '50%': { boxShadow: '0 0 0 18px rgba(240,127,37,0.06), 0 0 75px rgba(240,127,37,0.4)' } },
        'node-float': { '50%': { transform: 'translateY(-5px)' } },
        'card-float': { '50%': { transform: 'translateX(5px)' } },
        'edge-spin': { to: { transform: 'translate(-50%,-50%) rotate(360deg)' } },
        'edge-pulse': { '50%': { boxShadow: '0 0 0 14px rgba(240,127,37,0.04), 0 0 60px rgba(240,127,37,0.35)' } },
        'edge-signal-float': { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
        'edge-stream': {
          '0%': { opacity: '0', transform: 'translateY(0) scale(0.5)' },
          '10%': { opacity: '0.8' },
          '90%': { opacity: '0.4' },
          '100%': { opacity: '0', transform: 'translateY(-220px) scale(1.2)' },
        },
        'zen-pulse-fade': { '0%,100%': { opacity: '0' }, '50%': { opacity: '0.5' } },
        'zen-flow-down': { to: { strokeDashoffset: '20' } },
        'zen-ring-spin': { to: { transform: 'translate(-50%,-50%) rotate(360deg)' } },
        'zen-core-pulse': {
          '0%,100%': { filter: 'drop-shadow(0 0 10px rgba(240,127,37,0.35))' },
          '50%': { filter: 'drop-shadow(0 0 22px rgba(240,127,37,0.6))' },
        },
        'zen-node-float': {
          '0%,100%': { transform: 'translate(-50%,-50%) translateY(0)' },
          '50%': { transform: 'translate(-50%,-50%) translateY(-4px)' },
        },
        'zen-layer-in': {
          from: { opacity: '0', transform: 'translateX(-12px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'orbit-rotate': { to: { transform: 'rotate(360deg)' } },
        'orbit-rotate-reverse': { to: { transform: 'rotate(-360deg)' } },
        'architecture-glow': {
          '0%,100%': { opacity: '0.65', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.08)' },
        },
        'float-a': { '50%': { marginTop: '-5px' } },
        'float-b': { '50%': { marginTop: '4px' } },
        'float-c': { '50%': { marginTop: '-3px' } },
        'connection-pulse': { '0%,100%': { opacity: '0.25' }, '50%': { opacity: '0.75' } },
        'data-travel': {
          from: { transform: 'translateY(-12px)', opacity: '0' },
          '30%': { opacity: '1' },
          to: { transform: 'translateY(12px)', opacity: '0' },
        },
        'stream-move': {
          from: { transform: 'translateY(-30px)', opacity: '0' },
          '30%': { opacity: '1' },
          to: { transform: 'translateY(160px)', opacity: '0' },
        },
        'layer-reveal': {
          from: { opacity: '0', transform: 'translateY(15px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'node-pulse': {
          '0%,100%': { opacity: '0.35', transform: 'scale(0.8)' },
          '50%': { opacity: '1', transform: 'scale(1.3)' },
        },
        'dot-appear': { from: { opacity: '0', transform: 'scale(0)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'dot-flicker': { '0%,100%': { opacity: '0.65' }, '50%': { opacity: '1' } },
        'route-flow': { from: { strokeDashoffset: '0' }, to: { strokeDashoffset: '-50' } },
        'pulse-travel': {
          '0%': { offsetDistance: '0%', opacity: '0' },
          '10%': { opacity: '1' },
          '80%': { opacity: '1' },
          '100%': { offsetDistance: '100%', opacity: '0' },
        },
        'hub-glow': {
          '0%,100%': { opacity: '0.25', transform: 'scale(0.85)' },
          '50%': { opacity: '0.7', transform: 'scale(1.15)' },
        },
        'center-pulse': { '0%,100%': { r: '4' }, '50%': { r: '5.5' } },
        'hub-pulse': { '0%': { r: '10', opacity: '0.7' }, '100%': { r: '30', opacity: '0' } },
        'network-pulse-alt': {
          '0%,100%': { opacity: '0.25', transform: 'scale(0.8)' },
          '50%': { opacity: '1', transform: 'scale(1.5)' },
        },
        'badge-pulse': {
          '0%,100%': { opacity: '0.1', transform: 'scale(0.95)' },
          '50%': { opacity: '0.35', transform: 'scale(1.05)' },
        },
        'mega-in': {
          from: { opacity: '0', transform: 'translateY(-8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'mega-node-pulse': {
          '0%,100%': { opacity: '0.45', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.35)' },
        },
        'mega-line-flow': { to: { strokeDashoffset: '-24' } },
        'mega-particle': {
          '0%': { offsetDistance: '0%', opacity: '0' },
          '12%': { opacity: '0.9' },
          '88%': { opacity: '0.9' },
          '100%': { offsetDistance: '100%', opacity: '0' },
        },
        'mega-glow': {
          '0%,100%': { opacity: '0.35' },
          '50%': { opacity: '0.7' },
        },
        'bar-rise': {
          from: { transform: 'scaleY(0)', opacity: '0' },
          to: { transform: 'scaleY(1)', opacity: '1' },
        },
        'cta-line-flow': { to: { strokeDashoffset: '-28' } },
        'cta-dot-pulse': {
          '0%,100%': { opacity: '0.4', transform: 'scale(0.8)' },
          '50%': { opacity: '1', transform: 'scale(1.3)' },
        },
        'cta-float': {
          '0%,100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        'cta-glow-pulse': {
          '0%,100%': { opacity: '0.5', transform: 'translate(-50%,-50%) scale(1)' },
          '50%': { opacity: '1', transform: 'translate(-50%,-50%) scale(1.1)' },
        },
        'cta-net-mesh': {
          '0%,100%': { opacity: '0.3' },
          '50%': { opacity: '0.6' },
        },
        'cta-net-flow': { to: { strokeDashoffset: '-22' } },
        'cta-net-glow': {
          '0%,100%': { opacity: '0.3', transform: 'scale(0.8)' },
          '50%': { opacity: '0.7', transform: 'scale(1.2)' },
        },
        'cta-net-drift-1': {
          '0%,100%': { transform: 'translate(0,0)' },
          '50%': { transform: 'translate(3px,-4px)' },
        },
        'cta-net-drift-2': {
          '0%,100%': { transform: 'translate(0,0)' },
          '50%': { transform: 'translate(-3px,3px)' },
        },
        'cta-net-drift-3': {
          '0%,100%': { transform: 'translate(0,0)' },
          '50%': { transform: 'translate(2px,-2px)' },
        },
        'cta-net-particle': {
          '0%,100%': { opacity: '0.08', transform: 'translate(0,0)' },
          '50%': { opacity: '0.15', transform: 'translate(4px,-6px)' },
        },
      },
      animation: {
        'caret-blink': 'caret-blink 1.1s ease-in-out infinite',
        'caret-flow': 'caret-flow 1.4s ease-in-out infinite',
        'data-flow': 'data-flow 3.8s linear infinite',
        'network-pulse': 'network-pulse 5s ease-in-out infinite',
        'core-glow': 'core-glow 3s ease-in-out infinite',
        'node-float': 'node-float 4s ease-in-out infinite',
        'card-float': 'card-float 4s ease-in-out infinite',
        'edge-spin': 'edge-spin 22s linear infinite',
        'edge-spin-reverse': 'edge-spin 14s linear infinite reverse',
        'edge-pulse': 'edge-pulse 3s ease-in-out infinite',
        'edge-signal-float': 'edge-signal-float 5s ease-in-out infinite',
        'edge-stream': 'edge-stream 4s linear infinite',
        'zen-pulse-fade': 'zen-pulse-fade 3s ease-in-out infinite',
        'zen-flow-down': 'zen-flow-down 3s linear infinite',
        'zen-ring-spin': 'zen-ring-spin 35s linear infinite',
        'zen-ring-spin-reverse': 'zen-ring-spin 24s linear infinite reverse',
        'zen-core-pulse': 'zen-core-pulse 4s ease-in-out infinite',
        'zen-node-float': 'zen-node-float 5s ease-in-out infinite',
        'zen-layer-in': 'zen-layer-in 0.5s ease-out both',
        'orbit-rotate': 'orbit-rotate 35s linear infinite',
        'orbit-rotate-reverse': 'orbit-rotate-reverse 45s linear infinite',
        'architecture-glow': 'architecture-glow 4s ease-in-out infinite',
        'float-a': 'float-a 5s ease-in-out infinite',
        'float-b': 'float-b 4.5s ease-in-out infinite',
        'float-c': 'float-c 5.5s ease-in-out infinite',
        'connection-pulse': 'connection-pulse 3s ease-in-out infinite',
        'data-travel': 'data-travel 3s linear infinite',
        'stream-move': 'stream-move 2s linear infinite',
        'layer-reveal': 'layer-reveal 0.8s ease-out both',
        'node-pulse': 'node-pulse 2s ease-in-out infinite',
        'dot-appear': 'dot-appear 2s ease-out both',
        'dot-flicker': 'dot-flicker 5s ease-in-out infinite',
        'route-flow': 'route-flow 4s linear infinite',
        'pulse-travel': 'pulse-travel 3.5s linear infinite',
        'hub-glow': 'hub-glow 3s ease-in-out infinite',
        'center-pulse': 'center-pulse 2s ease-in-out infinite',
        'hub-pulse': 'hub-pulse 2.5s ease-out infinite',
        'network-pulse-alt': 'network-pulse-alt 2.5s ease-in-out infinite',
        'badge-pulse': 'badge-pulse 3s ease-in-out infinite',
        'mega-in': 'mega-in 180ms ease-out both',
        'mega-node-pulse': 'mega-node-pulse 2.8s ease-in-out infinite',
        'mega-line-flow': 'mega-line-flow 4.5s linear infinite',
        'mega-particle': 'mega-particle 5.5s linear infinite',
        'mega-glow': 'mega-glow 3.2s ease-in-out infinite',
        'bar-rise': 'bar-rise 0.8s ease-out both',
        'cta-line-flow': 'cta-line-flow 4s linear infinite',
        'cta-dot-pulse': 'cta-dot-pulse 2.5s ease-in-out infinite',
        'cta-float': 'cta-float 5s ease-in-out infinite',
        'cta-glow-pulse': 'cta-glow-pulse 4s ease-in-out infinite',
        'cta-net-mesh': 'cta-net-mesh 6s ease-in-out infinite',
        'cta-net-flow': 'cta-net-flow 8s linear infinite',
        'cta-net-glow': 'cta-net-glow 4s ease-in-out infinite',
        'cta-net-drift-1': 'cta-net-drift-1 7s ease-in-out infinite',
        'cta-net-drift-2': 'cta-net-drift-2 9s ease-in-out infinite',
        'cta-net-drift-3': 'cta-net-drift-3 8s ease-in-out infinite',
        'cta-net-particle': 'cta-net-particle 6s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
