-- Default CMS admin. Change this password on first login.
-- Email: admin@example.com
-- Password: ChangeMe123!
INSERT INTO admins (email, password_hash, name, role, status)
VALUES (
  'admin@example.com',
  '$2b$10$llxCd1o8eI4hLkOji.IWh.Il7Fvio1vKxyiYVNRdQrLb8QrxfPPHW',
  'Administrator',
  'admin',
  'active'
)
ON DUPLICATE KEY UPDATE email = email;

INSERT INTO settings (`key`, `value`) VALUES
  ('site_name', 'Zenium'),
  ('logo', ''),
  ('favicon', ''),
  ('contact_email', 'info@zenium.ai'),
  ('contact_phone', ''),
  ('contact_address', '')
ON DUPLICATE KEY UPDATE `key` = `key`;

-- CMS Pages SEO registry (slug = public path without leading /; homepage = home).
-- Sync live DB without full re-seed: node scripts/seed-pages.mjs
INSERT INTO pages (title, slug, content, status, seo_title, seo_description) VALUES
('Zenium | Energy Intelligence Platform for Smart Utilities', 'home', '', 'published', 'Zenium | Energy Intelligence Platform for Smart Utilities', 'Zenium is a utility intelligence company helping utilities turn metering and operational data into actionable intelligence, built on a trusted Head-End System (HES) and Meter Data Management System (MDMS) foundation.'),
('Advanced Metering Infrastructure (AMI) Software | Zenium', 'solutions/advanced-metering-infrastructure-ami', '', 'published', 'Advanced Metering Infrastructure (AMI) Software | Zenium', 'Scalable Advanced Metering Infrastructure (AMI) software platform. Hardware-agnostic HES, MDMS, and analytics for smart grid distribution utilities.'),
('Smart Meter Head-End System (HES) Software | Zenium', 'solutions/head-end-system-hes', '', 'published', 'Smart Meter Head-End System (HES) Software | Zenium', 'Enterprise Head-End System (HES) software for large-scale AMI rollouts. Vendor-agnostic DLMS/COSEM support, RF Mesh, and Cellular connectivity.'),
('Meter Data Management System (MDMS) Software | Zenium', 'solutions/meter-data-management-system-mdms', '', 'published', 'Meter Data Management System (MDMS) Software | Zenium', 'Enterprise Meter Data Management System (MDMS). Automate VEE, meter-to-cash billing determinants, prepayment, and energy theft detection.'),
('Utility & Smart Grid Analytics Software | Zenium', 'solutions/energy-management-analytics', '', 'published', 'Utility & Smart Grid Analytics Software | Zenium', 'Turn interval meter data into actionable intelligence. Transformer load profiling, non-technical loss analytics, and feeder balance monitoring.'),
('How to Read a Smart Meter Display | Zenium', 'guides/how-to-read-a-smart-meter-display', '', 'published', 'How to Read a Smart Meter Display | Zenium', 'Learn how to read smart meter display codes and understand common meter readings. Built for consumers and utilities exploring Advanced Metering Infrastructure (AMI).'),
('Watts to kWh Calculator | Convert Power to Energy Units | Zenium', 'tools/watts-to-kwh-calculator', '', 'published', 'Watts to kWh Calculator | Convert Power to Energy Units | Zenium', 'Convert watts or kilowatts to kilowatt-hours (kWh). Understand that 1 unit of electricity equals 1 kWh, then explore Zenium AMI, HES and MDMS software.'),
('Intelligence for Electricity, Gas and Water | Zenium', 'serve/utilities', '', 'published', 'Intelligence for Electricity, Gas and Water | Zenium', 'Zenium helps electricity, gas and water utilities connect infrastructure, manage trusted data and turn operational signals into actionable intelligence with Head-End System (HES), Meter Data Management System (MDMS) and Analytics.'),
('Intelligence for Connected Urban Infrastructure | Zenium', 'serve/cities', '', 'published', 'Intelligence for Connected Urban Infrastructure | Zenium', 'Zenium helps cities and infrastructure operators connect distributed assets, manage operational data and build greater visibility across connected urban environments.'),
('C&I Energy Data and Business Intelligence | Zenium', 'serve/commercial', '', 'published', 'C&I Energy Data and Business Intelligence | Zenium', 'Zenium helps commercial and industrial organisations gain greater visibility into energy consumption across sites, meters and operations.'),
('Intelligence for Distributed Energy Systems | Zenium', 'serve/microgrid', '', 'published', 'Intelligence for Distributed Energy Systems | Zenium', 'Zenium helps bring distributed energy data together to create greater visibility into generation, storage, consumption and system performance.'),
('Intelligence on Both Sides of the Meter | Zenium', 'serve/prosumers', '', 'published', 'Intelligence on Both Sides of the Meter | Zenium', 'Zenium helps organisations bring consumption and generation data together to create a clearer view of their changing energy position.'),
('Partners for AMI and Utility Solutions | Zenium', 'partners', '', 'published', 'Partners for AMI and Utility Solutions | Zenium', 'Zenium works with AMISPs, meter manufacturers and system integrators to connect smart-meter infrastructure, manage trusted data and support evolution towards Advanced Metering Infrastructure (AMI) 2.0.'),
('About Zenium | Utility Intelligence Company', 'company/about', '', 'published', 'About Zenium | Utility Intelligence Company', 'Zenium is a utility intelligence company helping utilities and the wider energy ecosystem turn metering and operational data into actionable intelligence.'),
('Careers in Energy Intelligence | Zenium', 'company/careers', '', 'published', 'Careers in Energy Intelligence | Zenium', 'Zenium combines deep utility expertise with smart-metering technology, analytics and AI. We look for people who want to help utilities turn data into intelligence.'),
('News and Insights on Utility Intelligence | Zenium', 'company/news', '', 'published', 'News and Insights on Utility Intelligence | Zenium', 'Perspectives, developments and ideas shaping the future of intelligent utility management from Zenium.'),
('Turning Utility Data Into Intelligent Action | Zenium', 'company/news/turning-utility-data-into-intelligent-action', '', 'published', 'Turning Utility Data Into Intelligent Action | Zenium', 'Utilities generate enormous volumes of data every day. The real opportunity is turning that information into insight — and insight into action.'),
('Contact Zenium | Utility Intelligence Enquiries', 'contact', '', 'published', 'Contact Zenium | Utility Intelligence Enquiries', 'Whether you are a utility, AMISP, meter manufacturer, technology partner or another organisation in the energy ecosystem, talk to Zenium about your requirements.'),
('Privacy Policy | Zenium', 'privacy', '', 'published', 'Privacy Policy | Zenium', 'This Privacy Policy explains how Zenix Data Private Limited, operating as Zenium, collects and uses information when you visit www.zenium.ai or contact us through the website.'),
('Terms of Use | Zenium', 'terms', '', 'published', 'Terms of Use | Zenium', 'Terms of Use for www.zenium.ai, operated by Zenix Data Private Limited under the brand name Zenium.'),
('Leadership | Zenium', 'company/leadership', '', 'published', 'Leadership | Zenium', 'Leadership page coming soon.'),
('Case Studies | Zenium', 'resources/case-studies', '', 'published', 'Case Studies | Zenium', 'Case studies page coming soon.'),
('Brochures | Zenium', 'resources/brochures', '', 'published', 'Brochures | Zenium', 'Brochures page coming soon.'),
('Whitepapers | Zenium', 'resources/whitepapers', '', 'published', 'Whitepapers | Zenium', 'Whitepapers page coming soon.'),
('Blogs & Insights | Zenium', 'resources/blogs-insights', '', 'published', 'Blogs & Insights | Zenium', 'Insights on Advanced Metering Infrastructure (AMI), Head-End System (HES), Meter Data Management System (MDMS) and utility analytics from Zenium.'),
('Webinars | Zenium', 'resources/webinars', '', 'published', 'Webinars | Zenium', 'Webinars page coming soon.')
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  status = VALUES(status),
  seo_title = VALUES(seo_title),
  seo_description = VALUES(seo_description);

-- FAQs are seeded from src/lib/seo/faqContent.ts via scripts/seed-faqs.mjs when DB is available.
-- Public pages fall back to faqContent.ts if the faqs table is empty.

-- FAQ seed from docs/FAQ.md (SEO notes stripped)
DELETE FROM faqs;
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('ami', 'What is Advanced Metering Infrastructure (AMI) and how does it work?', 'Advanced Metering Infrastructure (AMI) is an integrated, two-way communications architecture that connects smart meters with utility central enterprise systems. Unlike legacy automated meter reading (AMR), which only offers one-way drive-by collection, AMI establishes continuous bidirectional telemetry over cellular, RF Mesh, or PLC networks. This foundation enables automated interval data collection, real-time power outage detection, remote load control, and dynamic consumer billing.', 0, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('ami', 'What are the core components of an end-to-end AMI smart metering architecture?', 'A utility-grade AMI architecture consists of four mission-critical tiers: Smart Field Devices capturing interval load data and tamper alerts; a Multi-Technology Communication Layer utilizing RF Mesh, Cellular, or PLC; a Head-End System (HES) managing direct hardware connections and remote commands; and a Meter Data Management System (MDMS) performing data cleansing (Validation, Editing, and Estimation (VEE)) and feeding billing systems.', 1, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('ami', 'What communication technologies are used for smart meter connectivity?', 'AMI architectures leverage diverse communication media based on geographic density and topography. Point-to-point Cellular networks (4G, 5G, NB-IoT) deliver direct connectivity ideal for widely dispersed rural areas and high-load installations without local gateways. RF Mesh networks utilize self-healing peer-to-peer radio meshes suited for high-density urban areas. Zenium''s software platform operates as a communication-agnostic layer, ingesting data across Cellular, RF Mesh, and PLC networks simultaneously.', 2, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('ami', 'What is a Head-End System (HES) and what software solutions does Zenium offer?', 'A Head-End System (HES) is the critical software gateway between physical field devices and back-office enterprise software. It directly orchestrates meter sessions, manages protocol translation (DLMS/COSEM), tracks network reachability, and executes firmware rollouts. Zenium delivers a high-throughput, pure-play HES software platform built on open standards, allowing utilities to monitor multi-vendor meter fleets on a unified dashboard without proprietary hardware lock-in.', 3, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('ami', 'What is an Energy Management Solution (EMS) and how does it support utility operations?', 'An Energy Management Solution (EMS) is an enterprise analytical platform designed to balance power demand, monitor asset loading, and optimize energy flows across distribution systems. Ingesting high-frequency interval telemetry from the AMI layer, Zenium''s EMS identifies feeder-level distribution bottlenecks, tracks peak usage, forecasts capacity constraints, and enables automated demand-response events to maintain grid balance at minimal operational cost.', 4, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('ami', 'How do smart metering software solutions help utilities reduce AT&C and revenue losses?', 'Smart metering software targets Aggregate Technical and Commercial (AT&C) losses by eliminating manual recording inaccuracies and closing the gap between energy generated and energy billed. The system captures instantaneous alerts including meter bypass, reverse current, neutral disconnection, and magnetic tampering. By comparing distribution transformer boundary meters with downstream consumer consumption, Zenium''s software pinpoints non-technical losses instantly.', 5, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('ami', 'How does Zenium software integrate with existing utility billing, CIS, and ERP platforms?', 'Zenium software integrates into core utility back-office systems through enterprise connectors, including REST APIs, asynchronous message queues (Kafka, RabbitMQ), and IEC 61968 (CIM) standards. This architecture enables continuous data synchronization with Customer Information Systems (CIS) and billing platforms (including SAP and Oracle Utilities), Outage Management Systems (OMS), and Geographic Information Systems (GIS) without disrupting legacy IT operations.', 6, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('ami', 'How does AMI improve grid reliability and power outage management?', 'AMI transforms passive meters into real-time grid-edge sensors. During power disruptions, meters dispatch immediate "last-gasp" alarm notifications through the Head-End System (HES) to the utility''s Outage Management System (OMS), mapping the outage scope before consumer call centers receive complaints. Following field repairs, the Head-End System (HES) triggers automated verification pings to confirm full power restoration across all circuits without sending manual line patrols.', 7, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('ami', 'What cybersecurity standards protect smart metering software platforms?', 'AMI platforms handle sensitive energy infrastructure data, requiring defense-in-depth protection. Zenium''s software adheres to strict security standards, using SSL/TLS encryption for network data transit and AES-128/256 standards for field device communications. The platform enforces granular Role-Based Access Control (RBAC), multi-factor authentication, non-repudiable audit logs, and undergoes regular third-party Vulnerability Assessment and Penetration Testing (VAPT).', 8, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('ami', 'How does smart metering enable consumer engagement and demand-side management?', 'Smart metering converts consumers from passive energy users into active grid participants. By presenting interval consumption metrics on consumer web and mobile applications, utilities give consumers visibility into daily usage patterns, power quality, and estimated bills. This visibility enables demand-side management programs where consumers adjust power consumption during peak tariff periods, reducing grid stress and lowering bills.', 9, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('ami', 'What is the difference between AMR and AMI smart metering?', 'Automated Meter Reading (AMR) is a legacy one-way communication setup where field meters transmit consumption totals via drive-by radio or handheld receivers solely for billing generation. Advanced Metering Infrastructure (AMI) provides continuous, two-way automated communication between meters and utility enterprise software. AMI supports 15-minute interval telemetry, remote supply connects/disconnects, over-the-air firmware upgrades, and instant power outage logging.', 10, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('ami', 'Why should utilities and system integrators choose Zenium over proprietary systems?', 'Unlike traditional metering vendors that lock utilities into single-source proprietary hardware and software stacks, Zenium provides an open, pure-play software platform. Operating on DLMS/COSEM open standards, Zenium enables utilities to manage multi-vendor smart meter fleets and diverse communication technologies on a single pane of glass. This hardware-agnostic stance prevents vendor lock-in, reduces procurement costs, and supports smooth scaling.', 11, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('hes', 'What is a Head-End System (HES) in smart metering?', 'A Head-End System (HES) is the central device orchestration and data acquisition software layer within an AMI deployment. It functions as the direct communication bridge between field-deployed smart meters and utility back-office enterprise systems. The Head-End System (HES) initiates and terminates meter connections, collects raw interval readings, tracks field events, and dispatches remote execution commands down to device microcontrollers.', 0, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('hes', 'How does a smart meter Head-End System work?', 'A Head-End System operates through a continuous, multi-step pipeline. It manages secure connection sessions over Cellular, RF Mesh, or PLC; pulls scheduled interval load profiles, daily billing logs, and alarms; decodes raw meter protocols (such as DLMS/COSEM) into structured formats; forwards cleansed raw data to upstream Meter Data Management System (MDMS) platforms via message queues; and transmits remote commands like disconnects and firmware updates down to field meters.', 1, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('hes', 'What is the difference between a Head-End System (HES) and a Meter Data Management System (MDMS)?', 'The Head-End System (HES) focuses on device-level communication, managing field networks, maintaining connection reachability, acquiring raw interval data, and sending hardware commands directly to physical meters. The Meter Data Management System (MDMS) is hardware-agnostic software that ingests raw meter reads from the Head-End System (HES) to conduct Validation, Editing, and Estimation (VEE), run complex tariff calculations, manage billing determinants, and deliver clean data to utility CIS and ERP platforms.', 2, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('hes', 'What are the key features of Zenium Head-End System software?', 'Zenium''s Head-End System (HES) software provides vendor-agnostic hardware interoperability using open protocols like DLMS/COSEM; simultaneous management of cellular, RF Mesh, and hybrid networks; automated gap reconciliation to recover missed meter reads; instant remote execution of disconnect/reconnect commands and over-the-air firmware updates; and real-time network health diagnostics with SLA tracking dashboards.', 3, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('hes', 'Can Zenium HES integrate with smart meters from different manufacturers?', 'Yes. Zenium Head-End System (HES) is developed on an open, hardware-agnostic architecture. Leveraging open standards—primarily DLMS/COSEM (IEC 62056)—the software communicates with smart meters from various domestic and international manufacturers on the same network. This enables utilities to procure meters competitively across multiple vendors, avoiding proprietary hardware lock-in and simplifying mixed-meter operations.', 4, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('hes', 'What remote operations can utilities execute through Zenium HES?', 'Zenium Head-End System (HES) empowers utility operators to execute comprehensive remote field operations from a centralized console: automated or manual execution of supply connect and disconnect switches, immediate on-demand polling of instant electrical parameters, batch deployment of over-the-air firmware patches with rollback safeguards, remote updates of billing calendars, and continuous clock synchronizations to eliminate drift.', 5, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('hes', 'How does Zenium HES handle network communication failures and missed meter readings?', 'To manage transient cellular disruptions, RF signal attenuation, and network congestion, Zenium Head-End System (HES) uses automated gap reconciliation algorithms. The system cross-references ingested intervals against expected read schedules. When gaps are detected, the Head-End System (HES) logs missing records and triggers scheduled, low-bandwidth retries during off-peak network windows, recovering missed daily and interval load profiles to maintain 99%+ billing SLA targets.', 6, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('hes', 'How does Zenium HES integrate with Meter Data Management (MDM) and enterprise systems?', 'Zenium Head-End System (HES) utilizes a dual-path integration model to balance massive data ingestion with low-latency operational control. High-volume, periodic data streams—such as daily billing records, interval load profiles, and event logs—are piped via reliable message brokers (Kafka/RabbitMQ) directly into the Meter Data Management System (MDMS). Operational, bi-directional commands—such as on-demand reads, instant disconnections, and status verifications—are processed instantly via secure REST APIs.', 7, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('hes', 'How scalable is Zenium HES for large-scale utility rollouts?', 'Zenium Head-End System (HES) is built on a cloud-native, microservices-driven architecture designed for horizontal scalability. As device counts increase, system ingestion nodes scale dynamically to handle high-throughput telemetry streams. This design allows deployments to expand smoothly from pilot projects of 10,000 meters to nationwide rollouts managing millions of endpoints without degradation in read rates or query latency.', 8, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('hes', 'What security certifications, encryption, and VAPT standards does Zenium HES follow?', 'Zenium Head-End System (HES) implements end-to-end security across all architectural layers. Communications with field devices and upstream systems are protected using SSL/TLS encryption and AES cryptographic suites. The system provides Role-Based Access Control (RBAC), multi-factor authentication, granular event logging, and regularly undergoes third-party Vulnerability Assessment and Penetration Testing (VAPT) to meet utility cybersecurity compliance standards.', 9, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('hes', 'How does a Head-End System ensure data integrity during collection?', 'The Head-End System (HES) protects raw data integrity by validating data packets against cryptographic signatures and protocol checksums at the exact moment of ingestion. It verifies timestamps, confirms packet sequences, and identifies corrupted or incomplete frames before passing data upstream. Any malformed payloads are isolated in an exception handling queue for diagnostic analysis, preventing corrupted reads from polluting upstream systems.', 10, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('hes', 'How does Zenium HES monitor AMI network health and field device SLAs?', 'Zenium Head-End System (HES) provides real-time visibility into overall network health through an integrated Network Management dashboard. Operators can track communication success rates, monitor meter reachability, identify emerging signal bottlenecks, and analyze SLA compliance trends. By surfacing offline devices and repeating transmission errors, the platform enables maintenance teams to take proactive corrective action before communication drops impact billing deadlines.', 11, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('mdms', 'What is a Meter Data Management System (MDMS) in smart metering?', 'A Meter Data Management System (MDMS) is enterprise software that ingests, cleanses, analyzes, and manages high-frequency interval consumption data gathered from smart meters. Serving as the central data clearinghouse between the Head-End System (HES) and utility operational systems, the Meter Data Management System (MDMS) performs automated Validation, Editing, and Estimation (VEE). This converts raw device telemetry into verified, billing-ready determinants for Customer Information Systems (CIS), billing platforms, and grid analytics engines.', 0, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('mdms', 'What is VEE (Validation, Editing, and Estimation) in an MDMS?', 'Validation, Editing, and Estimation (VEE) is the core algorithmic framework within a Meter Data Management System (MDMS) that guarantees data accuracy prior to billing. Validation evaluates incoming interval data against configurable rules to identify anomalies like negative reads or sudden spikes. Editing flags and logs unverified records while maintaining an immutable audit log. Estimation automatically reconstructs missing interval profiles using historical baselines, surrounding peer comparisons, or seasonal interpolation.', 1, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('mdms', 'What is the operational difference between an HES and an MDMS?', 'The boundary between a Head-End System (HES) and a Meter Data Management System (MDMS) reflects the difference between device communications and business logic. The Head-End System (HES) connects directly to field meters, translates device protocols (DLMS/COSEM), monitors network uptime, and executes device-level commands. The Meter Data Management System (MDMS) operates downstream, receiving raw interval reads from one or more Head-End System (HES) instances, cleansing the data through Validation, Editing, and Estimation (VEE) rules, applying utility billing parameters, and delivering clean data to CIS and ERP systems.', 2, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('mdms', 'How does an MDMS integrate with utility billing and ERP systems?', 'A Meter Data Management System (MDMS) acts as the central integration engine for utility meter-to-cash operations. After interval reads clear Validation, Editing, and Estimation (VEE) processing, the Meter Data Management System (MDMS) computes billing determinants—such as total kWh, peak kW demand, power factor penalties, and Time-of-Use (TOU) allocations. It then delivers these billing-ready packages directly to Customer Information Systems (CIS) and ERP platforms (such as SAP, Oracle Utilities) via standard IEC 61968 CIM message schemas and secure REST APIs.', 3, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('mdms', 'Can an MDMS manage data from multiple Head-End Systems and diverse meter types?', 'Yes. An enterprise Meter Data Management System (MDMS) is completely independent of field-level communication networks and meter hardware brands. It unifies meter data ingestion across multiple Head-End Systems, distinct network types (Cellular, RF Mesh, PLC), and multiple utility commodities (electricity, water, gas). This consolidates utility operations onto a single platform, eliminating the need for disconnected, commodity-specific data silos.', 4, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('mdms', 'How does an MDMS help utilities detect energy theft and non-technical losses (NTL)?', 'A Meter Data Management System (MDMS) pinpoints non-technical losses by correlating meter event records with interval consumption patterns. It monitors tamper notifications—such as meter cover openings, magnetic tamper events, neutral disturbances, and current reversals—alongside sudden drops in consumption. By comparing boundary distribution transformer (DT) meters against aggregate consumer consumption on the same circuit, the Meter Data Management System (MDMS) flags unmetered power use, allowing utilities to dispatch revenue protection teams efficiently.', 5, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('mdms', 'How does an MDMS support prepaid smart metering operations?', 'A Meter Data Management System (MDMS) enables prepaid smart metering by tracking consumption against consumer financial balances in near real-time. The platform applies active tariff structures to incoming interval reads, calculates deductions, and triggers balance status updates to customer mobile applications. When account balances fall below zero, the Meter Data Management System (MDMS) dispatches an automated disconnection order through the Head-End System (HES) to trip the meter''s load switch, and triggers immediate reconnection once account recharges are verified.', 6, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('mdms', 'How does an MDMS handle Time-of-Use (TOU) and dynamic tariff billing?', 'As power systems adopt dynamic pricing, a Meter Data Management System (MDMS) processes 15-minute or 30-minute interval data into configurable tariff windows (such as Peak, Off-Peak, and Critical Peak). The system easily accommodates seasonal rate changes, weekend schedules, and demand-response event rates. It prepares pre-calculated tariff determinants for the billing system without requiring manual parameter reconfigurations on field-deployed meters.', 7, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('mdms', 'How scalable is a cloud-native Meter Data Management System?', 'Enterprise smart meter rollouts produce massive volumes of interval telemetry. A cloud-native Meter Data Management System (MDMS) handles this data using distributed big data frameworks, horizontal microservice scaling, and cloud storage architectures. This architecture ensures high ingestion throughput, rapid Validation, Editing, and Estimation (VEE) processing, and low-latency historical reporting whether managing a regional pilot of 50,000 meters or an interconnected national network of over 10 million endpoints.', 8, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('mdms', 'How does an MDMS ensure meter data security, privacy, and regulatory compliance?', 'A Meter Data Management System (MDMS) maintains data integrity through strict governance controls. It provides granular Role-Based Access Control (RBAC), end-to-end data encryption for storage and transit, and logs every automated calculation, user intervention, and data edit in an immutable audit trail. These mechanisms ensure full compliance with national data privacy standards and regulatory utility reporting mandates.', 9, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('mdms', 'What advanced grid analytics can utilities derive from an MDMS?', 'Beyond billing generation, a Meter Data Management System (MDMS) provides advanced grid-edge analytics. By aggregating interval load telemetry, the system enables transformer load profiling to detect overloaded assets, phase balancing analytics to map feeder imbalances and minimize line losses, load forecasting based on historical usage and weather models, and monitoring reverse power flows to optimize electric vehicle charging and rooftop solar integration.', 10, 1);
INSERT INTO faqs (page_key, question, answer, sort_order, enabled) VALUES ('mdms', 'How does an MDMS manage multi-commodity meter data (Electricity, Gas, and Water)?', 'A unified Meter Data Management System (MDMS) processes diverse utility commodities within a single platform. It uses commodity-specific validation engines and engineering unit conversions—translating kilowatt-hours for electricity, cubic meters for water, and thermal units for gas. This multi-commodity support allows dual-fuel and municipal multi-utilities to operate a consolidated software platform, lowering IT infrastructure overhead and unifying customer billing statements.', 11, 1);
